import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Router from "next/router";
import {Footer} from "../components";
import {Button} from "@nextui-org/react";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Button
          onClick={() => {
            Router.push('/profile');
          }}
        >
          Mon profil
        </Button>


        You are now logged in !
      </main>

      <Footer />
    </div>
  )
}
